Repository coda/packs-sdk, pull requests merged in 2023-07, with the labels that each got.

#2668 Update docs for property options
  api.ts
  api_types.ts
  dist/api.d.ts
  dist/api.js
  dist/api_types.d.ts
  dist/api_types.js
  dist/bundle.d.ts
  dist/bundle.js
  dist/index.d.ts
  dist/index.js
  dist/schema.d.ts
  docs/guides/blocks/sync-tables/two-way.md
  docs/reference/sdk/enums/core.OptionsType.md
  docs/reference/sdk/functions/core.makeDynamicSyncTable.md
  docs/reference/sdk/interfaces/core.DynamicOptions.md
  docs/reference/sdk/interfaces/core.DynamicSyncTableDef.md
  docs/reference/sdk/interfaces/core.DynamicSyncTableOptions.md
  docs/reference/sdk/interfaces/core.ExecutionContext.md
  docs/reference/sdk/interfaces/core.PropertyOptionsExecutionContext.md
  docs/reference/sdk/modules/core.md
  docs/reference/sdk/types/core.PropertyOptionsMetadataFunction.md
  index.ts
  schema.ts
  typedoc.js
Labels: documentation

#2622 Update dependency dts-bundle-generator to v8
  dist/bundle.d.ts
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2580 Update dependency @types/node to v18.16.19
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2669 Fix video loading on certain browsers
  docs/images/auth_sign_in.mp4
  docs/images/cli_rebuild.mp4
  docs/images/dynamic_sync_table_usage.mp4
  docs/images/home_demo.mp4
  docs/images/sync_table_use.mp4
  docs/images/tutorial_formula_slash.mp4
  docs/images/two_way.mp4
  docs/images/web_ide_build.mp4
  docs/images/web_ide_navigate.mp4
  docs/images/web_ide_rebuild.mp4
  docs/images/web_ide_use.mp4
Labels: documentation

#2671 Remove mkdocs-video plugin
  Pipfile
  Pipfile.lock
  docs/guides/basics/authentication/index.md
  docs/guides/blocks/sync-tables/dynamic.md
  docs/guides/blocks/sync-tables/index.md
  docs/guides/blocks/sync-tables/two-way.md
  docs/index.md
  docs/tutorials/build/formula.md
  docs/tutorials/get-started/.cli/core.md
  docs/tutorials/get-started/.rebuild.md
  docs/tutorials/get-started/.use.md
  docs/tutorials/get-started/github.md
  docs/tutorials/get-started/gitpod.md
  docs/tutorials/get-started/replit.md
  docs/tutorials/get-started/web.md
  mkdocs.yml
  requirements.txt
Labels: documentation

#2672 Update dependency esbuild to v0.18.11
  bundles/thunk_bundle.js
  dist/bundle.js
  dist/bundles/thunk_bundle.js
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2623 Update dependency glob to v10
  documentation/scripts/typedoc_post_process.ts
  package.json
  pnpm-lock.yaml
  test/doc_formatting_test.ts
Labels: dependencies, javascript, renovate

#2675 Update dependency semver to v7.5.4
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2676 Add sample Pack demonstrating property options
  cspell.yml
  docs/embedded-snippets/samples/packs/two-way/splitwise.html
  docs/samples/topic/two-way.md
  documentation/generated/examples.json
  documentation/samples/packs/two-way/splitwise.ts
  documentation/scripts/documentation_config.ts
Labels: documentation

#2626 Update dependency typescript to v5.1.6
  dist/api.js
  dist/api_types.js
  dist/cli/config_storage.js
  dist/cli/extensions.js
  dist/documentation/types.js
  dist/helpers/external-api/v1.js
  dist/helpers/legacy_marshal/constants.js
  dist/helpers/svg.js
  dist/runtime/common/marshaling/constants.js
  dist/runtime/common/marshaling/index.js
  dist/runtime/common/marshaling/serializer.js
  dist/runtime/types.js
  dist/schema.js
  dist/testing/compile.js
  dist/testing/constants.js
  dist/types.js
  docs/reference/sdk/classes/core.PackDefinitionBuilder.md
  docs/reference/sdk/functions/core.makeDynamicSyncTable.md
  docs/reference/sdk/functions/core.makeSyncTable.md
  package.json
  pnpm-lock.yaml
  requirements.txt
Labels: dependencies, javascript, renovate

#2685 Update dependency certifi to v2023.7.22 [SECURITY]
  requirements.txt
Labels: dependencies, python, renovate
