Repository coda/packs-sdk, pull requests merged in 2023-10, with the labels that each got.

#2761 Update dependency bracex to v2.4
  requirements.txt
Labels: dependencies, python, renovate

#2762 Update dependency cffi to v1.16.0
  requirements.txt
Labels: dependencies, python, renovate

#2765 Update dependency mkdocs to v1.5.3
  requirements.txt
Labels: dependencies, python, renovate

#2766 Update dependency mkdocs-material-extensions to v1.2
  requirements.txt
Labels: dependencies, python, renovate

#2755 Update dependency urllib3 to v2.0.6
  requirements.txt
Labels: dependencies, python, renovate

#2767 Prepare for two-way sync going live
  docs/guides/advanced/schemas.md
  docs/guides/advanced/two-way-sync.md
  docs/guides/blocks/actions.md
  docs/guides/blocks/sync-tables/index.md
  docs/guides/blocks/sync-tables/two-way.md
  docs/samples/topic/two-way.md
  documentation/generated/examples.json
  documentation/scripts/documentation_config.ts
  mkdocs.yml
Labels: documentation

#2714 Update dependency cairosvg to v2.7.1
  requirements.txt
Labels: dependencies, python, renovate, stale

#2716 Update dependency click to v8.1.7
  requirements.txt
Labels: dependencies, python, renovate, stale

#2720 Update dependency lxml to v4.9.3
  requirements.txt
Labels: dependencies, python, renovate, stale

#2722 Update dependency mkdocs-macros-plugin to v1.0.4
  requirements.txt
Labels: dependencies, python, renovate, stale

#2724 Update dependency pyyaml to v6.0.1
  requirements.txt
Labels: dependencies, python, renovate, stale

#2769 Remove tip about ID properties
  docs/guides/advanced/schemas.md
Labels: documentation

#2768 Update Todoist sample with 2way
  docs/embedded-snippets/samples/packs/todoist/full.html
  docs/samples/full/todoist.md
  documentation/generated/examples.json
  documentation/samples/packs/todoist/full.ts
Labels: documentation

#2772 Update docs for deferred auth
  Makefile
  docs/guides/basics/authentication/index.md
  docs/images/auth_sign_in.mp4
  docs/images/tutorial_oauth_complete.png
  docs/images/tutorial_oauth_complete_2x.png
  docs/images/tutorial_oauth_connect.png
  docs/images/tutorial_oauth_connect_2x.png
  docs/images/tutorial_oauth_signin.png
  docs/images/tutorial_oauth_signin_2x.png
  docs/images/two_way_autocomplete.png
  docs/images/two_way_autocomplete_2x.png
  docs/images/two_way_enable.png
  docs/images/two_way_enable_2x.png
  docs/images/two_way_error.png
  docs/images/two_way_error_2x.png
  docs/tutorials/build/oauth.md
Labels: documentation

#2773 Update docs with new column picker UI
  docs/guides/blocks/sync-tables/index.md
  docs/images/sync_table_select_columns.png
  docs/images/sync_table_select_columns_2x.png
Labels: documentation

#2774 Add information on obtaining the filename of a file parameter
  docs/guides/basics/parameters/index.md
Labels: documentation

#2770 Update dependency zod to v3.22.3 [SECURITY]
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2739 Update dependency @types/express to v4.17.18
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2741 Update dependency @types/js-yaml to v4.0.6
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2743 Update dependency @types/mock-fs to v4.13.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2740 Update dependency @types/fs-extra to v11.0.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2744 Update dependency @types/proxyquire to v1.3.29
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2742 Update dependency @types/mocha to v10.0.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2746 Update dependency @types/readline-sync to v1.4.5
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2748 Update dependency @types/sha.js to v2.4.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2750 Update dependency @types/uglify-js to v3.17.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2745 Update dependency @types/qs to v6.9.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2752 Update dependency @types/xml2js to v0.4.12
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2753 Update dependency @types/yargs to v17.0.26
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2759 Update dependency @types/node to v18.18.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2754 Update dependency chai to v4.3.10
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2764 Update dependency eslint to v8.51.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2760 Update dependency aws-sdk to v2.1473.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2758 Update aws-sdk-js-v3 monorepo to v3.428.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2729 Update dependency esbuild to v0.19.4
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2756 Update dependency uuid to v9.0.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2781 Update dependency urllib3 to v2.0.7 [SECURITY]
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2723 Update dependency mkdocs-redirects to v1.2.1
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2721 Update dependency mkdocs-awesome-pages-plugin to v2.9.2
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2793 Update dependency mkdocs-macros-plugin to v1.0.4
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2776 Update dependency pillow to v10 [SECURITY]
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2792 Update dependency cairosvg to v2.7.1
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2779 Clarify that card subtitles fallback to featured properties
  docs/guides/blocks/cards.md
Labels: documentation

#2800 Update typescript-eslint monorepo to v6 (major)
  dev/eslint/rules/base_rules.js
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate
