Repository coda/packs-sdk, pull requests merged in 2023-04, with the labels that each got.

#2543 Update dependency mkdocs-material to v9.1.5
  requirements.txt
Labels: dependencies, python, renovate

#2540 Update dependency @types/yargs to v17.0.24
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2542 Update dependency fs-extra to v11.1.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2551 Update dependency cspell to v6.31.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2549 Update dependency @types/node to v18.15.11
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2548 Update aws-sdk-js-v3 monorepo to v3.303.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2545 Update dependency sharp-cli to v4.1.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2546 Update dependency sinon to v15.0.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2557 Update dependency xml2js to v0.5.0 [SECURITY]
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2558 Fix breaking changes in MkDocs Material 9
  mkdocs.yml
Labels: documentation

#2568 Remove beta label from cards
  docs/guides/blocks/cards.md
  docs/samples/topic/card.md
  documentation/generated/examples.json
  documentation/samples/packs/card/README.md
  documentation/scripts/documentation_config.ts
Labels: documentation

#2569 Add documentation for card placeholders
  docs/guides/advanced/schemas.md
  docs/images/schemas_placeholders.png
  docs/images/schemas_placeholders_2x.png
Labels: documentation

#2571 Add markup rendering examples.
  docs/guides/basics/data-types.md
Labels: documentation

#2572 Document searchDynamicUrls
  CHANGELOG.md
  docs/embedded-snippets/samples/packs/dynamic-sync-table/open_data_ny.html
  docs/embedded-snippets/samples/packs/dynamic-sync-table/typeform.html
  docs/guides/best-practices.md
  docs/guides/blocks/sync-tables/dynamic.md
  docs/images/dynamic_sync_table_search.png
  docs/images/dynamic_sync_table_search_2x.png
  docs/samples/topic/dynamic-sync-table.md
  documentation/generated/examples.json
  documentation/samples/packs/dynamic-sync-table/open_data_ny.ts
  documentation/samples/packs/dynamic-sync-table/typeform.ts
Labels: documentation
