Repository coda/packs-sdk, pull requests merged in 2023-11, with the labels that each got.

#2812 Update dependency @types/browserify to v12.0.39
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2814 Update dependency @types/clone to v2.1.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2816 Update dependency @types/express to v4.17.20
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2818 Update dependency @types/js-yaml to v4.0.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2820 Update dependency @types/mock-fs to v4.13.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2822 Update dependency @types/pascalcase to v1.0.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2824 Update dependency @types/qs to v6.9.9
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2826 Update dependency @types/semver to v7.5.4
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2811 Update aws-cli orb to v4.1.1
  .circleci/config.yml
Labels: dependencies, renovate, circleci

#2813 Update dependency @types/chai to v4.3.9
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2821 Update dependency @types/node to v18.18.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2827 Update dependency @types/sha.js to v2.4.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2810 Pin dependencies
  runtime/native/node18/x86_64/isolated-vm/package.json
Labels: dependencies, javascript, renovate

#2815 Update dependency @types/exorcist to v2.0.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2817 Update dependency @types/fs-extra to v11.0.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2819 Update dependency @types/mocha to v10.0.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2823 Update dependency @types/proxyquire to v1.3.30
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2825 Update dependency @types/readline-sync to v1.4.6
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2830 Add two-way sync webinar recording to the docs
  docs/guides/blocks/sync-tables/two-way.md
  docs/tutorials/videos.md
Labels: documentation

#2832 Update pnpm to >=8.0.0 <8.10.1
  package.json
  requirements.txt
Labels: dependencies, javascript, renovate
