Repository coda/packs-sdk, pull requests merged in 2023-09, with the labels that each got.

#2710 Update dependency @types/semver to v7.5.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2712 Update dependency @types/sinon to v10.0.16
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2713 Update dependency @types/uuid to v9.0.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2715 Update dependency chai to v4.3.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2708 Add information about HTTP debug logs
  docs/guides/development/troubleshooting.md
  docs/support/faq.md
Labels: documentation

#2709 Update dependency @types/node to v18.17.12
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2711 Update dependency @types/sha.js to v2.4.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2717 Update dependency cross-fetch to v3.1.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2719 Update dependency handlebars to v4.7.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2718 Update dependency cspell to v6.31.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2725 Update dependency ts-loader to v9.4.4
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2726 Update aws-cli orb to v4.1.0
  .circleci/config.yml
Labels: dependencies, renovate, circleci

#2727 Update aws-sdk-js-v3 monorepo to v3.398.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2730 Update dependency eslint to v8.48.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2728 Update dependency aws-sdk to v2.1447.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2738 Un-hide some fields and types related to two-way sync
  api.ts
  dist/api.d.ts
  dist/bundle.d.ts
  dist/schema.d.ts
  docs/reference/sdk/interfaces/core.ObjectSchemaProperty.md
  docs/reference/sdk/modules/core.md
  docs/reference/sdk/types/core.GenericSyncUpdate.md
  docs/reference/sdk/types/core.GenericSyncUpdateSingleResult.md
  schema.ts
Labels: documentation
