Repository coda/packs-sdk, pull requests merged in 2023-08, with the labels that each got.

#2677 More specific typing for PropertyOptionsExecutionContext.propertySchema
  api_types.ts
  dist/api_types.d.ts
  dist/bundle.d.ts
  dist/runtime/types.d.ts
  docs/reference/sdk/interfaces/core.PropertyOptionsExecutionContext.md
  runtime/types.ts
Labels: stale, keep-active

#2698 Fix broken link in reference docs
  api.ts
  dist/api.d.ts
  dist/api.js
  dist/bundle.d.ts
  docs/reference/sdk/functions/core.makeSyncTable.md
Labels: documentation

#2687 Update dependency urllib3 to v2.0.4
  requirements.txt
Labels: dependencies, python, renovate

#2688 Update dependency xml2js to v0.6.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2689 Update aws-sdk-js-v3 monorepo
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2691 Update dependency aws-sdk to v2.1430.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2692 Update dependency cairocffi to v1.6.1
  requirements.txt
Labels: dependencies, python, renovate

#2693 Update dependency charset-normalizer to v3.2.0
  requirements.txt
Labels: dependencies, python, renovate

#2695 Update dependency importlib-metadata to v6.8.0
  requirements.txt
Labels: dependencies, python, renovate

#2697 Update dependency mkdocs to v1.5.2
  requirements.txt
Labels: dependencies, python, renovate

#2694 Update dependency eslint to v8.46.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2690 Update dependency @types/node to v18.17.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2696 Update dependency markdown to v3.4.4
  requirements.txt
Labels: dependencies, python, renovate

#2699 Two-way sync updates
  docs/guides/advanced/schemas.md
  docs/guides/basics/data-types.md
  docs/guides/blocks/sync-tables/two-way.md
Labels: documentation
