Repository coda/packs-sdk, pull requests merged in 2023-03, with the labels that each got.

#2475 Update dependency yargs to ^17.7.1
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2473 Pin dependencies
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2481 Update dependency markupsafe to v2.1.2
  requirements.txt
Labels: dependencies, python, renovate

#2482 Update dependency minimist to v1.2.8
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2484 Update dependency mkdocs-material-extensions to v1.1.1
  requirements.txt
Labels: dependencies, python, renovate

#2485 Update dependency requests to v2.28.2
  requirements.txt
Labels: dependencies, python, renovate

#2483 Update dependency mkdocs-material to v8.5.11
  requirements.txt
Labels: dependencies, python, renovate

#2486 Update dependency urllib3 to v1.26.14
  requirements.txt
Labels: dependencies, python, renovate

#2499 Update dependency @types/express to v4.17.17
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2500 Update dependency @types/uuid to v9.0.1
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2502 Update dependency node-fetch to v2.6.9
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2477 Update dependency zod to v3.20.6
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2503 Update dependency open to v8.4.2
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2487 Update dependency cairosvg to v2.6.0
  requirements.txt
Labels: dependencies, python, renovate

#2506 Update aws-sdk-js-v3 monorepo
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2507 Update dependency aws-sdk to v2.1325.0
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2488 Update dependency cspell to v6.27.0
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2490 Update dependency importlib-metadata to v5.2.0
  requirements.txt
Labels: dependencies, python, renovate

#2512 Update dependency eslint to v8.35.0
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2492 Update dependency natsort to v8.3.1
  requirements.txt
Labels: dependencies, python, renovate

#2493 Update dependency pillow to v9.4.0
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2494 Update dependency pygments to v2.14.0
  requirements.txt
Labels: dependencies, python, renovate

#2496 Update dependency termcolor to v2.2.0
  requirements.txt
Labels: dependencies, python, renovate

#2498 Update dependency zipp to v3.15.0
  requirements.txt
Labels: dependencies, python, renovate

#2495 Update dependency pymdown-extensions to v9.9.2
  requirements.txt
Labels: dependencies, python, renovate

#2497 Update dependency watchdog to v2.3.1
  requirements.txt
Labels: dependencies, python, renovate

#2511 Update dependency esbuild to v0.17.10
  bundles/thunk_bundle.js
  dist/bundles/thunk_bundle.js
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2516 Update typescript-eslint monorepo to v5.54.0
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2510 Update dependency aws-sdk to v2.1326.0
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2509 Update aws-sdk-js-v3 monorepo to v3.282.0
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2489 Update dependency glob to v8.1.0
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2515 Update jq orb to v1.10.0
  .circleci/config.yml
Labels: dependencies, renovate, circleci

#2501 Update dependency @types/yargs to v17.0.22
  cli/coda.ts
  documentation/scripts/documentation_publisher.ts
  package.json
  yarn.lock
Labels: dependencies, javascript, renovate

#2508 Update dependency release-it to v15.7.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2524 Update contributing instructions for pnpm
  CONTRIBUTING.md
Labels: documentation

#2463 Experimental "propertyAutocomplete" for sync tables
  api.ts
  api_types.ts
  builder.ts
  bundles/thunk_bundle.js
  dist/api.d.ts
  dist/api.js
  dist/api_types.d.ts
  dist/builder.d.ts
  dist/builder.js
  dist/bundle.d.ts
  dist/bundle.js
  dist/bundles/thunk_bundle.js
  dist/helpers/migration.d.ts
  dist/helpers/migration.js
  dist/index.d.ts
  dist/runtime/thunk/thunk.js
  dist/runtime/types.d.ts
  dist/runtime/types.js
  dist/schema.d.ts
  dist/schema.js
  dist/testing/execution.js
  dist/testing/upload_validation.js
  docs/reference/sdk/functions/core.makeDynamicSyncTable.md
  docs/reference/sdk/interfaces/core.EmailSchema.md
  helpers/migration.ts
  index.ts
  runtime/thunk/thunk.ts
  runtime/types.ts
  schema.ts
  test/api_test.ts
  test/schema_test.ts
  test/upload_validation_test.ts
  testing/execution.ts
  testing/upload_validation.ts
Labels: keep-alive

#2527 Add Slack auth sample
  docs/embedded-snippets/samples/packs/apis/slack.html
  docs/samples/topic/apis.md
  documentation/generated/examples.json
  documentation/samples/packs/apis/slack.ts
  documentation/scripts/documentation_config.ts
Labels: documentation

#2532 Add Markdown parameter to documentation
  docs/guides/basics/parameters/index.md
Labels: documentation

#2529 Add docs and samples for AWS auth
  docs/embedded-snippets/samples/packs/authentication/aws.html
  docs/embedded-snippets/samples/packs/image/aws_s3.html
  docs/guides/basics/authentication/index.md
  docs/samples/topic/apis.md
  docs/samples/topic/authentication.md
  docs/samples/topic/image.md
  documentation/generated/examples.json
  documentation/samples/packs/authentication/aws.ts
  documentation/samples/packs/image/README.md
  documentation/samples/packs/image/aws_s3.ts
  documentation/scripts/documentation_config.ts
Labels: documentation

#2537 Add transfer Pack ownership info to FAQ
  docs/support/faq.md
Labels: documentation
