Repository coda/packs-sdk, pull requests merged in 2023-06, with the labels that each got.

#2625 Update dependency open to v9
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2624 Update dependency mkdocs-macros-plugin to v1
  requirements.txt
Labels: dependencies, python, renovate

#2619 Update actions/stale action to v8
  .github/workflows/stale.yml
Labels: dependencies, renovate

#2618 Update actions/checkout action to v3
  .github/workflows/release.yml
Labels: dependencies, renovate

#2621 Update dependency @aws-crypto/sha256-js to v4
  package.json
  pnpm-lock.yaml
  requirements.txt
Labels: dependencies, javascript, renovate

#2620 Update aws-cli orb to v4
  .circleci/config.yml
Labels: dependencies, renovate, circleci

#2609 Update dependency pillow to v9.5.0
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#2550 Update dependency aws-sdk to v2.1348.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2541 Update dependency esbuild to v0.17.14
  dist/bundle.js
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2578 Update dependency yargs to v17.7.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2611 Update dependency semver to v7.5.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2615 Update dependency zod to v3.21.4
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2614 Update dependency xml2js to v0.6.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2616 Update typescript-eslint monorepo to v5.59.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2610 Update dependency release-it to v15.10.5
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2641 Update dependency regex to v2023.6.3
  requirements.txt
Labels: dependencies, python, renovate

#2639 Update dependency ts-loader to v9.4.3
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2638 Update dependency remark-lint-no-undefined-references to v4.2.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2632 Update dependency @types/chai to v4.3.5
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2636 Update dependency markupsafe to v2.1.3
  requirements.txt
Labels: dependencies, python, renovate

#2635 Update dependency esbuild to v0.17.19
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2634 Update dependency cross-fetch to v3.1.6
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2640 Update dependency aws-sdk to v2.1390.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2584 Update dependency markdown to v3.4.3
  requirements.txt
Labels: dependencies, python, renovate

#2581 Update dependency eslint to v8.42.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2637 Update dependency qs to v6.11.2
  bundles/thunk_bundle.js
  dist/bundle.js
  dist/bundles/thunk_bundle.js
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2654 Rebrand the 2way beta as an alpha
  docs/guides/blocks/sync-tables/two-way.md
  docs/samples/topic/two-way.md
  documentation/generated/examples.json
  documentation/samples/packs/two-way/README.md
Labels: documentation

#2658 Misc docs additions
  docs/guides/advanced/caching.md
  docs/guides/basics/fetcher.md
Labels: documentation

#2659 Update alpha warning message
  docs/guides/blocks/sync-tables/two-way.md
  docs/samples/topic/two-way.md
  documentation/generated/examples.json
  documentation/samples/packs/two-way/README.md
Labels: documentation

#2667 Add docs and samples for MultiHeaderToken
  docs/embedded-snippets/samples/packs/authentication/copper.html
  docs/embedded-snippets/samples/snippets/authentication/user_multi_header.html
  docs/guides/basics/authentication/index.md
  docs/samples/topic/apis.md
  docs/samples/topic/authentication.md
  documentation/generated/examples.json
  documentation/generated/pack.code-snippets
  documentation/generated/snippets.json
  documentation/samples/packs/authentication/copper.ts
  documentation/samples/snippets/authentication/user_multi_header.ts
  documentation/scripts/documentation_config.ts
Labels: documentation
