Repository coda/packs-sdk, pull requests merged in 2024-01, with the labels that each got.

#2887 Document two-way behavior with `fromKey`
  docs/guides/blocks/sync-tables/two-way.md
Labels: documentation

#2899 Add docs for CLI metadata formula execution
  docs/guides/development/cli.md
Labels: documentation

#2886 Advanced property options feature to ignore properties when caching
  api.ts
  bundles/thunk_bundle.js
  dist/api.d.ts
  dist/bundles/thunk_bundle.js
  dist/runtime/thunk/thunk.js
  runtime/thunk/thunk.ts
Labels: keep-active

#2902 Remove guidance against `id` properties
  docs/embedded-snippets/samples/packs/github/full.html
  docs/embedded-snippets/samples/packs/image/dropbox.html
  docs/embedded-snippets/samples/packs/image/google_drive.html
  docs/embedded-snippets/samples/packs/todoist/card.html
  docs/embedded-snippets/samples/packs/todoist/column_format.html
  docs/embedded-snippets/samples/packs/todoist/formula.html
  docs/embedded-snippets/samples/packs/todoist/full.html
  docs/embedded-snippets/samples/packs/todoist/reference.html
  docs/embedded-snippets/samples/packs/todoist/schema.html
  docs/embedded-snippets/samples/packs/todoist/sync_table.html
  docs/embedded-snippets/samples/packs/todoist/update.html
  docs/embedded-snippets/samples/packs/two-way/splitwise.html
  docs/embedded-snippets/samples/snippets/schema/object_schema_sync.html
  docs/embedded-snippets/samples/snippets/sync_table.html
  docs/guides/advanced/schemas.md
  docs/guides/best-practices.md
  docs/guides/blocks/actions.md
  docs/guides/blocks/sync-tables/dynamic.md
  docs/guides/design.md
  docs/samples/full/github.md
  docs/samples/full/todoist.md
  docs/samples/topic/action.md
  docs/samples/topic/card.md
  docs/samples/topic/column-format.md
  docs/samples/topic/formula.md
  docs/samples/topic/image.md
  docs/samples/topic/schema.md
  docs/samples/topic/sync-table.md
  docs/samples/topic/two-way.md
  docs/support/migration/v0.11.0.md
  docs/tutorials/build/sync-table.md
  documentation/generated/examples.json
  documentation/generated/pack.code-snippets
  documentation/generated/snippets.json
  documentation/samples/packs/github/full.ts
  documentation/samples/packs/image/dropbox.ts
  documentation/samples/packs/image/google_drive.ts
  documentation/samples/packs/todoist/card.ts
  documentation/samples/packs/todoist/column_format.ts
  documentation/samples/packs/todoist/formula.ts
  documentation/samples/packs/todoist/full.ts
  documentation/samples/packs/todoist/reference.ts
  documentation/samples/packs/todoist/schema.ts
  documentation/samples/packs/todoist/simple.ts
  documentation/samples/packs/todoist/sync_table.ts
  documentation/samples/packs/todoist/update.ts
  documentation/samples/packs/tutorials/sync-table/build1.ts
  documentation/samples/packs/tutorials/sync-table/build2.ts
  documentation/samples/packs/tutorials/sync-table/build3.ts
  documentation/samples/packs/two-way/splitwise.ts
  documentation/samples/snippets/schema/object_schema_sync.ts
  documentation/samples/snippets/sync_table.ts
Labels: documentation

#2905 Add more fetcher samples
  cspell.yml
  docs/embedded-snippets/samples/packs/fetcher/imgur.html
  docs/embedded-snippets/samples/packs/fetcher/mock_shop.html
  docs/guides/advanced/caching.md
  docs/guides/basics/fetcher.md
  docs/samples/topic/fetcher.md
  documentation/generated/examples.json
  documentation/samples/packs/fetcher/imgur.ts
  documentation/samples/packs/fetcher/mock_shop.ts
  documentation/scripts/documentation_config.ts
Labels: documentation

#2850 Update dependency @types/qs to v6.9.11
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate, stale

#2860 Update dependency esbuild to v0.20.0
  dist/bundle.js
  package.json
  pnpm-lock.yaml
  requirements.txt
Labels: dependencies, javascript, renovate

#2889 Update dependency ts-node to v10.9.2
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate
