Repository coda/packs-sdk, pull requests merged in 2024-03, with the labels that each got.

#2907 Update dependency @types/uuid to v9.0.8
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2920 Update dependency esbuild to v0.20.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2919 Update aws-cli orb to v4.1.3
  .circleci/config.yml
Labels: dependencies, renovate, circleci

#2918 Update dependency mocha to v10.3.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2847 Update dependency @types/node to v18.19.18
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2875 Update pnpm to v8.15.4
  package.json
Labels: dependencies, javascript, renovate

#2917 Update dependency eslint to v8.57.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2916 Update dependency aws-sdk to v2.1566.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2915 Update aws-sdk-js-v3 monorepo to v3.521.0
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#2926 Add documentation for displayName
  docs/embedded-snippets/samples/packs/dynamic-sync-table/open_data_ny.html
  docs/embedded-snippets/samples/packs/dynamic-sync-table/typeform.html
  docs/guides/advanced/schemas.md
  docs/samples/topic/dynamic-sync-table.md
  documentation/generated/examples.json
  documentation/samples/packs/dynamic-sync-table/open_data_ny.ts
  documentation/samples/packs/dynamic-sync-table/typeform.ts
Labels: documentation

#2927 Fixes to displayName documentation
  docs/guides/advanced/schemas.md
Labels: documentation
