Repository coda/packs-sdk, pull requests merged in 2024-12, with the labels that each got.

#3122 Update dependency mkdocs-redirects to v1.2.2
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies, python, renovate

#3095 Update dependency browserify to v17.0.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate, stale

#3108 Update dependency @release-it/keep-a-changelog to v5
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate, stale

#3013 Update pnpm to v9
  package.json
  pnpm-lock.yaml
Labels: dependencies, javascript, renovate

#3131 Disable the Browserify polyfill for vm
  .eslintrc.js
  cli/extensions.ts
  cli/link.ts
  dist/testing/compile.js
  documentation/scripts/readthedocs_preprocess.ts
  test/auth_test.ts
  test/compile_test.ts
  test/packs/fake_with_vm.ts
  testing/compile.ts
  testing/helpers.ts
Labels: stale
